[project]
name = "fastserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.14",
    "influxdb>=5.3.2",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "requests>=2.32.4",
    "uvicorn>=0.35.0",
]
